/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DTO.CadastrarDTO;
import DTO.UsuarioDTO;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private UsuarioDTO usuarioLogado;

    public TelaPrincipal(CadastrarDTO usuario) {
        initComponents();

        UsuarioDTO usuarioDTO = new UsuarioDTO();
        usuarioDTO.setId_usuario(usuario.getIdCadastro()); // Certifique-se de que getId() existe
        usuarioDTO.setNome_usuario(usuario.getNome());
        this.usuarioLogado = usuarioDTO;

        txtBnv.setText("Bem-vindo, " + usuarioLogado.getNome_usuario() + "!");

        if ("admin".equals(usuarioLogado.getNome_usuario())) {
            ativarFuncoesAdmin();
        } else {
            ativarFuncoesUsuario();
        }

    }

    private void ativarFuncoesAdmin() {

        subMenuAdcFilmes.setEnabled(true);
        subMenuAdcUsu.setEnabled(true);

    }

    private void ativarFuncoesUsuario() {
        subMenuAdcFilmes.setEnabled(false);
        subMenuAdcUsu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtBnv = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subMenuAdcFilmes = new javax.swing.JMenuItem();
        subMenuAdcUsu = new javax.swing.JMenuItem();
        subMenuCatálogo = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("MyNetFlix");

        txtBnv.setText("Bem vindo, usuário!");

        jMenu1.setText("Funções");

        subMenuAdcFilmes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        subMenuAdcFilmes.setText("Adicionar filmes");
        subMenuAdcFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMenuAdcFilmesMousePressed(evt);
            }
        });
        subMenuAdcFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAdcFilmesActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuAdcFilmes);

        subMenuAdcUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        subMenuAdcUsu.setText("Adcionar usuários");
        subMenuAdcUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subMenuAdcUsuMouseClicked(evt);
            }
        });
        subMenuAdcUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAdcUsuActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuAdcUsu);

        subMenuCatálogo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        subMenuCatálogo.setText("Catálogo");
        subMenuCatálogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMenuCatálogoMousePressed(evt);
            }
        });
        subMenuCatálogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCatálogoActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuCatálogo);

        jMenuBar1.add(jMenu1);

        menuAjuda.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sobre");
        menuAjuda.add(jMenuItem1);

        jMenuBar1.add(menuAjuda);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtBnv))
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBnv)
                .addGap(18, 18, 18)
                .addComponent(Desktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarAdmin() {
        subMenuAdcFilmes.setEnabled(true);
        txtBnv.setForeground(Color.PINK);
        txtBnv.repaint();

    }

    public void setUsuario(String nome) {
        txtBnv.setText("Bem vindo, " + nome + "!");

        if (nome != null && nome.trim().equalsIgnoreCase("admin")) {
            subMenuAdcFilmes.setEnabled(true);
            txtBnv.setForeground(Color.PINK);
        } else {
            subMenuAdcFilmes.setEnabled(false);
            txtBnv.setForeground(Color.BLACK);
        }
    }


    private void subMenuCatálogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCatálogoActionPerformed

    }//GEN-LAST:event_subMenuCatálogoActionPerformed

    private void subMenuCatálogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuCatálogoMousePressed
        if (usuarioLogado == null) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário logado!");
            return;
        }

        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();
        }

        Catalogo cata = new Catalogo(usuarioLogado);
        cata.setVisible(true);
        Desktop.add(cata);
        try {
            cata.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }

        System.out.println("Catálogo funcionando");
    }//GEN-LAST:event_subMenuCatálogoMousePressed

    private void subMenuAdcFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAdcFilmesActionPerformed
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();
        }

        Filmes f1 = new Filmes();
        f1.setVisible(true);
        Desktop.add(f1);
        try {
            f1.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }

        System.out.println("Filmes funcionando");
    }//GEN-LAST:event_subMenuAdcFilmesActionPerformed

    private void subMenuAdcFilmesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuAdcFilmesMousePressed

    }//GEN-LAST:event_subMenuAdcFilmesMousePressed

    private void subMenuAdcUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAdcUsuActionPerformed
      Cadastrar c1 = new Cadastrar ();
      c1.setVisible(true);

    }//GEN-LAST:event_subMenuAdcUsuActionPerformed

    private void subMenuAdcUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuAdcUsuMouseClicked

    }//GEN-LAST:event_subMenuAdcUsuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarDTO usuarioTeste = new CadastrarDTO();
                usuarioTeste.setNome("visitante"); // ou admin/teste
                new TelaPrincipal(usuarioTeste).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenu menuAjuda;
    public static javax.swing.JMenu menuSair;
    public javax.swing.JMenuItem subMenuAdcFilmes;
    private javax.swing.JMenuItem subMenuAdcUsu;
    public static javax.swing.JMenuItem subMenuCatálogo;
    public javax.swing.JLabel txtBnv;
    // End of variables declaration//GEN-END:variables
}
