/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;
import javax.swing.JMenuItem;

/**
 *
 * @author aluno.saolucas
 */
public class TelaPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        subMenuAdcFilmes.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtBnv = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subMenuAdcFilmes = new javax.swing.JMenuItem();
        subMenuCatálogo = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("MyNetFlix");

        txtBnv.setText("Bem vindo, usuário!");

        jMenu1.setText("Funções");

        subMenuAdcFilmes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        subMenuAdcFilmes.setText("Adicionar filmes");
        subMenuAdcFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMenuAdcFilmesMousePressed(evt);
            }
        });
        subMenuAdcFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAdcFilmesActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuAdcFilmes);

        subMenuCatálogo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        subMenuCatálogo.setText("Catálogo");
        subMenuCatálogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMenuCatálogoMousePressed(evt);
            }
        });
        subMenuCatálogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCatálogoActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuCatálogo);

        jMenuBar1.add(jMenu1);

        menuAjuda.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sobre");
        menuAjuda.add(jMenuItem1);

        jMenuBar1.add(menuAjuda);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBnv)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(txtBnv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarAdmin() {
        subMenuAdcFilmes.setEnabled(true);
        txtBnv.setForeground(Color.PINK);
        txtBnv.repaint();

    }

    public void setUsuario(String nome) {
        txtBnv.setText("Bem vindo, " + nome + "!");

        if (nome != null && nome.trim().equalsIgnoreCase("admin")) {
            subMenuAdcFilmes.setEnabled(true);
            txtBnv.setForeground(Color.PINK);
        } else {
            subMenuAdcFilmes.setEnabled(false);
            txtBnv.setForeground(Color.BLACK);
        }
    }


    private void subMenuCatálogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCatálogoActionPerformed

    }//GEN-LAST:event_subMenuCatálogoActionPerformed

    private void subMenuCatálogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuCatálogoMousePressed
        Catalogo cata = new Catalogo();
        cata.setVisible(true);
        Desktop.add(cata);
        System.out.println("asdsaasdas");
    }//GEN-LAST:event_subMenuCatálogoMousePressed

    private void subMenuAdcFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAdcFilmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuAdcFilmesActionPerformed

    private void subMenuAdcFilmesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuAdcFilmesMousePressed
        Filmes f1 = new Filmes(); 
        f1.setVisible(true);
        Desktop.add(f1);
        System.out.println("Filme funcionando");
    }//GEN-LAST:event_subMenuAdcFilmesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenu menuAjuda;
    public static javax.swing.JMenu menuSair;
    public javax.swing.JMenuItem subMenuAdcFilmes;
    public static javax.swing.JMenuItem subMenuCatálogo;
    public javax.swing.JLabel txtBnv;
    // End of variables declaration//GEN-END:variables
}
